[package]
name = "key-encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
aes = "0.7.0"
block-modes = "0.8.0"
block-padding = "0.2.1"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
rand = "0.8.5"
hex = "0.4.3"
secp256k1 = "0.24"