[package]
name = "sig-compare"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = { version = "2.0"}
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
hex = "0.4"
sha3 = "0.10.6"
